### ISSUE TITLE
Log dart messages to file

### ISSUE THREAD

**Issue by holzeis** [itchysats/10101#103]
https://medium.com/flutter-community/logging-in-flutter-a583b3668228

**Comment by klochowicz** [comment]
is it expected that we don't see any flutter logs on stdout anymore? we might not notice e.g. exceptions or other relevant stuff, especially when we pipe things from Rust there now too.

**Comment by holzeis** [comment]
@klochowicz I've updated the title of the ticket. By introducing FLog the logs are still printed to stdout, but also stored to a database. It will allow us to easily share the logs eventually. If by file or differently is up to decide in #105 .

**Comment by klochowicz** [comment]
@holzeis the reason I'm asking is that they are not visible anymore on stdout - unless it's just my machine ?

**Comment by holzeis** [comment]
@klochowicz oh ok, well they are visible on my machine.

**Comment by klochowicz** [comment]
> @klochowicz oh ok, well they are visible on my machine.

is there something I need to set to make them appear again?

**Comment by holzeis** [comment]
Ok, after a quick alignment, it seems the debug messages are not printed anymore. I will create a follow up PR for that.

**Comment by klochowicz** [comment]
> Ok, after a quick alignment, it seems the debug messages are not printed anymore. I will create a follow up PR for that.

they're not even the "debug" messages yet - because we don't explicitly set the log level from Rust -  seems that all msgs from Rust are affected.

**Comment by holzeis** [comment]
> > Ok, after a quick alignment, it seems the debug messages are not printed anymore. I will create a follow up PR for that.
> 
> they're not even the "debug" messages yet - because we don't explicitly set the log level from Rust - seems that all msgs from Rust are affected.

All rust messages are currently logged on debug level

https://github.com/itchysats/10101/blob/156b0c1cb38c54d622b33f9cdcab6ed02dbc452f/lib/main.dart#L134-L138

**Comment by klochowicz** [comment]
I'll fix that part when we add support for tracing (should be up tomorrow, I have it started)

**Comment by holzeis** [comment]
https://github.com/itchysats/10101/pull/129
