### ISSUE TITLE
Share log messages

### ISSUE THREAD

**Issue by holzeis** [itchysats/10101#105]
Dependent on #103 and #83.

We need a way to share log files from the TenTenOne App with us. using FLog we can make use of the `FLog.exportLogs()`

**Comment by klochowicz** [comment]
under what circumstances do you envision sharing? the OS infra in an event of the crash, or a button that you can use at any time?

**Comment by holzeis** [comment]
Either like described here https://github.com/itchysats/10101/pull/104#discussion_r1011211396 or in a support case. I have apps where I can check the logs and create a support email request from them automatically.

**Comment by klochowicz** [comment]
> Either like described here [#104 (comment)](https://github.com/itchysats/10101/pull/104#discussion_r1011211396) or in a support case. I have apps where I can check the logs and create a support email request from them automatically.

I'm sorry, it's still not too clear. Perhaps I will rephrase: would it be sufficient if we leaned on OS functionality to send logs over? (not sure how this works on Android, but on iOS it's super easy, especially with TestFlight. simple on macOS too in an event of a crash).

**Comment by holzeis** [comment]
> > Either like described here [#104 (comment)](https://github.com/itchysats/10101/pull/104#discussion_r1011211396) or in a support case. I have apps where I can check the logs and create a support email request from them automatically.
> 
> I'm sorry, I'm still unsure how you picture this. Perhaps I will rephrase: would it be sufficient if we leaned on OS functionality to send logs over? (not sure how this works on Android, but on iOS it's super easy, especially with TestFlight. simple on macOS too in an event of a crash).

Well, I don't know yet 🙂, I don't have the most mobile development experience and I would need to read into that topic a little bit more. Your suggestion of leaning on the infra sounds good to me.

**Comment by klochowicz** [comment]
> > > Either like described here [#104 (comment)](https://github.com/itchysats/10101/pull/104#discussion_r1011211396) or in a support case. I have apps where I can check the logs and create a support email request from them automatically.
> > 
> > 
> > I'm sorry, I'm still unsure how you picture this. Perhaps I will rephrase: would it be sufficient if we leaned on OS functionality to send logs over? (not sure how this works on Android, but on iOS it's super easy, especially with TestFlight. simple on macOS too in an event of a crash).
> 
> Well, I don't know yet 🙂, I don't have the most mobile development experience and I would need to read into that topic a little bit more. Your suggestion of leaning on the infra sounds good to me.

I'll dig around for it a bit and will let you know what I came up with.

**Comment by holzeis** [comment]
Thank you
