### ISSUE TITLE
Create wallet upon first start

### ISSUE THREAD

**Issue by holzeis** [itchysats/10101#11]
Upon first start of the app a wallet needs to be generated utilizing the Bip39 standard. This may be implemented using a combination of the [bitcoindevkit](https://bitcoindevkit.org/) and the [lightningdevkit](https://lightningdevkit.org/)

**Acceptance Criterias**

- lightning wallet (on & off chain) is initialized and ready to use (exposed through the flutter_rust_bridge)
- a simple view showing the current balance - demonstrating that the wallet can be accessed from the view.

**Comment by holzeis** [comment]
This issue is not intended to make the wallet already 100% usable, but get to a point where we feel comfortable of making it usable. Follow up issues may be required!

**Comment by klochowicz** [comment]
@holzeis I've noticed we're both assigned to it - how would you like to split the work? would you like to pair on this?

**Comment by bonomat** [comment]
I thought I'd share some insights: 
rust-lightning is very modular, meaning, we will need to implement various things. Among others, rust-lightning does not take care of an on-chain wallet for you but asks you to perform certain tasks and hand over the signed transactions to the ldk. 
This means, we can implement an on-chain wallet using BDK as we are used to. 

Sample code: here they use bitcoind's wallet: 

https://github.com/lightningdevkit/ldk-sample/blob/8984205acf1d328837d0f33798e89e479aea1882/src/main.rs#L147-L165

**Comment by holzeis** [comment]
thanks for the input. I will have a look..

**Comment by klochowicz** [comment]
@holzeis do you think we can close it? on-chain wallet is initialised, balance is displayed, and the off-chain wallet is covered by #82

**Comment by holzeis** [comment]
> @holzeis do you think we can close it? on-chain wallet is initialised, balance is displayed, and the off-chain wallet is covered by #82

yes.
