### ISSUE TITLE
Create PPP for the first iteration

### ISSUE THREAD

**Issue by holzeis** [itchysats/10101#12]
Write up and publish the PPP (Plan, Progress, Problems) as weekly report to https://makers.bolt.fun/project/10101

### Example PPPs
- https://makers.bolt.fun/story/ppps-week-1-lightsats--207
- https://makers.bolt.fun/story/ppps-week-1--160

**Comment by bonomat** [comment]
In here the recommendation is to post it by Monday each week: https://makers.bolt.fun/story/how-to-buildinpublic--169
