### ISSUE TITLE
Legends of Lightning Tournament

### ISSUE THREAD

**Issue by holzeis** [itchysats/10101#130]
This issue summarizes the goals / features for the legends of lightning tournament.

**Release app on desktop and android.** 

- [x] #128 
- [ ] #79 
- [ ] #133 
- [x] #30 
- [x] #9 

****

**The taker gets a full fledged on and off-chain wallet**

* This will allow the user to receive and send on-chain and off-chain funds
* The taker runs a full lightning node running on her phone.
* Use electrum (instead of bitcoind) to monitor onchain transactions.
* Taker opens an uni-directional lightning channel with maker with funds provided by the maker.

- [x] #125 
- [x] #100 
- [x] #102 
- [x] #11
- [x] #68 
- [x] #113 
- [x] #165
- [x] #114 
- [x] #132 
- [x] #82 
- [x] #10 
- [x] #139 

****

**The maker runs a full lightning node server side.** 
(would be cool if this could also work eventually on the phone 😉 )

* Simple HTTP apis to fetch offers, propose settlement, etc.

- [x] #89 
- [x] #106 

****

**Taker can trade a non-perpetual CFD position.**

* Only happy case

- [x] #106 
- [x] #126 
- [x] #87 
- [x] #115 
- [x] https://github.com/itchysats/rust-lightning/issues/2
- [x] #85 
- [x] #126

**Comment by da-kami** [comment]
Note: Keeping the list of tickets up to date is hard, so I added the `Legends of Lightning` label to the tickets to be actioned, see: https://github.com/itchysats/10101/labels/Legends%20of%20Lightning

**Comment by holzeis** [comment]
I am closing this issue as the tournament is over!
