### ISSUE TITLE
Create a lightning invoice to receive money

### ISSUE THREAD

**Issue by holzeis** [itchysats/10101#132]
Something similar to how it looks in the breez app.

![Image](https://user-images.githubusercontent.com/382048/200279942-8ac9f118-cbf0-48e4-96cd-207fdeb09a3d.png)

**Comment by holzeis** [comment]
@da-kami can you pick up a wire frame design?

**Comment by da-kami** [comment]
Will integrate a simple flow in the wireframes and then ping here!

**Comment by da-kami** [comment]
![ReceivePayment-UserJourney](https://user-images.githubusercontent.com/5557790/201550755-3c2cb012-1db7-4e6e-9244-7d86444e9f35.png)

**Comment by luckysori** [comment]
As discussed, removing my assignment in case @holzeis wants to work on it whilst Australia sleeps. Otherwise I can pick it up again in the morning.

**Comment by klochowicz** [comment]
#251 adds most of the plumbing for this and verifies that it works on the maker side.
What will be still left would be piping through the desired args (expiry time and amount), and rendering the QR code.

**Comment by klochowicz** [comment]
Implemented in #289
