### ISSUE TITLE
Containerize maker

### ISSUE THREAD

**Issue by holzeis** [itchysats/10101#180]

**Comment by klochowicz** [comment]
I've tried to quickly cobble something together: #205 , however @bonomat rightly pointed out the following:

> given we only have one binary, we don't need this complex action and can go for a predefined [action](https://github.com/marketplace/actions/build-and-push-docker-images)

I've unassigned myself from it as I've got other things to deal with first.

**Comment by bonomat** [comment]
Resolved in https://github.com/itchysats/10101/pull/233
