### ISSUE TITLE
Support regtest

### ISSUE THREAD

**Issue by klochowicz** [itchysats/10101#181]
Supporting regtest will speed up testing. It would involve passing custom Electrum server URL to your local instance and allowing overwriting the bitcoin network from the outside (for flutter, probably via env variable as well).

**Comment by klochowicz** [comment]
By using `nigiri`, and exposing the bdk wallet address, we can have an easy way of adding funds via faucet.

**Comment by bonomat** [comment]
I've pushed this here: https://github.com/itchysats/10101/tree/add-maker-binary-electrs-on-regtest

There is not much to `setup` locally besides installing [nigiri](https://github.com/vulpemventures/nigiri) and running `nigiri start`. 

Once you have your address you can fund it with

```
nigiri faucet <address>
```

To generate a block, the easiest way is to just call the faucet again.

**Comment by klochowicz** [comment]
done as a part of #187
