### ISSUE TITLE
Close CFD

### ISSUE THREAD

**Issue by holzeis** [itchysats/10101#183]
Wiring the frontend/taker with the maker, removing the custom output for closing a cfd (dlc) position.

**Comment by holzeis** [comment]
@luckysori can you create a follow up PR for the settlement amounts? I guess this has todo with the payout curves?

**Comment by luckysori** [comment]
> @luckysori can you create a follow up ticket for the settlement amounts? I guess this has to do with the payout curves?

Here it is: https://github.com/itchysats/10101/issues/219.

**Comment by holzeis** [comment]
thanks
