### ISSUE TITLE
Send funds from maker to taker for channel opening

### ISSUE THREAD

**Issue by da-kami** [itchysats/10101#199]
In our regtest setup the taker currently has funds and just opens the channel sending 2/3 of the channel capacity to the maker. 

This does not not reflect the flow we agreed upon for the tournament:

1. Contact the maker for opening a channel (HTTP endpoint)
    1. The taker provides a Bitcoin address for funding
    2. The taker defines "how much funds the taker" wants to use for trading in the channel; the channel capacity is 1/3 taker, 2/3 maker.
     1.  The taker's `Open Channel` screen should not talk about the capacity, that's confusing - it should talk about how much funds the taker wants to use for trading in the channel.
     1. (The maker could respond with maker's connection details) -> Hardcode the maker details in the taker will do
1. The maker sends the 2/3 of funds to the taker's Bitcoin address
    1. I think the taker's user interface should not  show this transaction otherwise that might be confusing, we might want to filter this address when displaying the history.
1. The taker opens a channel with the taker+maker amount and sends the maker BTC back to the maker as part of channel opening
    1. The taker can only open the channel once the funds of the maker are in mempool, so we will need an `Opening Channel` state in the payment list which spins until the channel is open. This is spinning while:
        1. Send the message to the maker
        2. Maker sends BTC 
        3. Taker sees BTC in mempool
        4. Taker triggers opening channel.  
        5. The channel is open - and usable...? see: https://github.com/itchysats/10101/issues/206

Notes:

- I don't think we have to keep any state on the maker side; the maker just sends out BTC when a taker's request comes in and expects that a channel will be opened and funds will be sent over through the channel open. (the maker acts as a testnet faucet :)
- The taker might have to persist the address that is used for channel opening so we can filter that address and not display it in the history (to avoid confusion :)

---

Note: This is obviously not safe for the maker and simplified to get a working version for the tournament. This should *never* be used in production!

**Comment by da-kami** [comment]
It will be easier to match on the funds arriving in mempool if the maker responds with the transaction ID that funds the address provided by the taker, so the maker should respond with the transaction ID.

**Comment by bonomat** [comment]
Sorry for slow reply. 
I think what you wrote up makes sense. Particularly this point is important: 

> The maker sends the 2/3 of funds to the taker's Bitcoin address
> 
>     1. I think the taker's user interface should not  show this transaction otherwise that might be confusing, we might want to filter this address when displaying the history.
