### ISSUE TITLE
Persist CFD data and custom output data for display and collab close on the taker

### ISSUE THREAD

**Issue by da-kami** [itchysats/10101#201]
The taker has to remember the `CustomOutputDetails` received during opening the CFD.

We will need a database to store this information alongside with the data that captured the opening ("initial") values of the Cfd.
You can refer to the `CfdDetail` screen and ItchySats to see what we need stored.

**Comment by bonomat** [comment]
https://github.com/itchysats/10101/pull/211 loads the payment history from lighting and displays it in the ui. Within this ticket I would expect to extend the list of `LightningTransactions` to also include the `Cfds` transactions.

**Comment by da-kami** [comment]
After discussion with @luckysori for our current solution with exactly one channel and one CFD we actualy don't have to store the `CustomOutputDetail` because we can just get it with `channel.first().outputs..first()` from the channel manager.

However, we will have to sage the initial values of the CFD to be able to come up with the payouts according to the price change. Note: This will require some kind of payout curve calc.

**Comment by bonomat** [comment]
> This will require some kind of payout curve calc as described in https://github.com/itchysats/10101/issues/219

No need for a payout curve, a simple formula like
`pnl = quantity_usd* ((1/price_opening)-(1/price_closing)`
should be sufficient.

**Comment by da-kami** [comment]
I'm closing this one with #231 - for any needed follow-ups please create specific tickets!
