### ISSUE TITLE
Do not hard-code settlement amounts

### ISSUE THREAD

**Issue by luckysori** [itchysats/10101#219]
With #207 we introduced the ability to actually settle CFDs (removing the custom output from the Lightning channel). But the values used are hard-coded in the frontend.

### Rough design
1. User navigates to CFD order details page (data loaded from storage, see #201).
2. User presses the `settle` button.
3. We use some of the persisted values together with the current price to call a `calculate_payouts_function` which acts as the payout curve.
4. The function returns `maker_amount` and `taker_amount` which can replace the hard-coded values.

https://github.com/itchysats/10101/blob/a91a50c3df483a95fa61e265d4671bb64286622f/lib/cfd_trading/cfd_order_detail.dart#L124

**Comment by bonomat** [comment]
waiting for https://github.com/itchysats/10101/pull/231 to land. I'll unasign myself in the meantime.
