### ISSUE TITLE
LOL Demo Video 

### ISSUE THREAD

**Issue by da-kami** [itchysats/10101#256]
Create a 5~ minutes video that showcases 10101 for the Ledgends of Lightning submission.

This is a demo video that is independent of recording the pitch video.

Includes: 

- [ ] Live demo + recording video of it
- [ ] Promote video on bolt.fun; this includes minutes description (can do on youtube as well)

**Comment by da-kami** [comment]
Video should align with #257

**Comment by bonomat** [comment]
Script: 

1. funding on-chain bitcoin
2. open channel 
4. open CFD
5. -- set maker spread negative to fake profit 
6. settle CFD
7. pay a LN invoice for your pina colada 
8. receive money via LN

**Comment by da-kami** [comment]
Demo Script Notes:

0. Prepare:

	- Reset the maker except seed
	- Start the maker and make sure it has funds
	- Reset the taker completely (including seed)
	- Start the taker on ios

	Taker dir:

	cd "/Users/dakami/Library/Developer/CoreSimulator/Devices/AC0BDAB2-39B9-416F-A019-740A348B5C9F/data/Containers/Data/Application/2D23C685-03BC-4356-B3C9-5D20ECCFB190/Library/Application Support"

- Terminal windows to prepare

	- nigiri faucet (taker)
	- nigiri faucet (random address to mine block)
	- curl for changing spread
	- curl to create invoice on maker

1. Set spread to 0

```
curl -X PUT http://127.0.0.1:8000/api/spread/0 # sets spread to 0.0
```

2. Fund the taker using the address and faucet

3. Open a channel with the maker

4. Open CFD

5. Set spread to minus

```
curl -X PUT http://127.0.0.1:8000/api/spread/-30 # sets spread to -0.03
```

6. Close CFD


7. Send Lightning payment

	- Create invoice on maker ("we deserve a drink")
	- Pay invoice of maker from taker ("Oh no, no split bills here, I'll pay for both of us, you can pay me back later")

```
curl -X GET http://localhost:8000/api/invoice/create
```

8. Create invoice on taker and receive payment

	- Create invoice on taker and pay it from maker

```
curl -X POST http://localhost:8000/api/invoice/send/lnbcrt100u1p3h6660dpqg4jzqurpd9jzqen0wgs8g6r9yp3x2etjnp4qd4ep4w4wqlut9kevgpnxxqnct6jypl6zev49y3nhtl34fa2ypzxxpp5gt2ljwlrf4h0nskdv460m0lwu4knu6f420ukzd9cx4g2lnlydhxqsp5804y4qdfuhlq4ga8raqz5te0l77e0s78t23jtwt70tdgw6zr68rs9qyysgqcqpcxqzjcrzjqt9k29ce83rxmcrg3w9s8pkmlvuajmpcg3f9cyc4639a3cggcz9uzqqqqqqqdxgqq5qqqqlgqqqqqqqqfqm5hd5e5jsmcwc33ehm09v5v849cr2zvhrx8jzglf37y098sx2tyyzm2wgdw8932cjzwtj9e6lltzexp5hqnrdyj2h24hqx4lyztffzqp49qhze

```

**Comment by holzeis** [comment]
> * Start the taker on ios
Shouldn't we go for android? After all, we always said - we are going for android first.

I don't know if it would improve the demonstration, but instead of using a simulator, we could actually run the app on the phone and stream the screen to the recording. e.g. https://www.makeuseof.com/tag/mirror-android-screen-pc-mac-without-root/

**Comment by da-kami** [comment]
https://makers.bolt.fun/story/10101-its-demo-time--470
