### ISSUE TITLE
Persist lightning payment history

### ISSUE THREAD

**Issue by klochowicz** [itchysats/10101#260]
I've noticed that my lightning payment history disappeared after restarting. We should persist it.

Note: it probably is not needed for the purpose of the tournament, as we can demo all the functionality in a single run.

**Comment by bonomat** [comment]
It's not persisted? 😲

**Comment by klochowicz** [comment]
> It's not persisted? 😲

when I run it today, I noticed that my Friday's transactions were not visible 😕

**Comment by da-kami** [comment]
I added the label, not sure this needs actioning?

**Comment by klochowicz** [comment]
@da-kami I removed the label, it does not need to be actioned for the demo, given we're doing everything from scratch there. It should be actioned afterwards.

**Comment by klochowicz** [comment]
It was not important for the demo, but crucial for any releases :-) otherwise the history is missing.
