### ISSUE TITLE
Create release

### ISSUE THREAD

**Issue by bonomat** [itchysats/10101#268]
* Release on GitHub
* Create milestone blogpost where we promote the release

**Comment by da-kami** [comment]
Would be cool if we can point the release against the testnet maker :)

**Comment by holzeis** [comment]
In order to release for testnet we need to resolve the following tickets.

- [ ] #336 
- [ ] #337 
- [ ] #339 
- [ ] #341 
- [ ] https://github.com/itchysats/10101/pull/335

Does not block the app release, but would be helpful to have right afterwards.

- [ ] #340

**Comment by luckysori** [comment]
@holzeis: I've created a project view with all the tickets you've mentioned here. It should be easier to track and to add new items if we need to.

**Comment by da-kami** [comment]
Closing this ticket because we did release `0.2.0` and `0.2.1`.
