### ISSUE TITLE
Calculate open-channel amount instead of pre-filling the complete balance

### ISSUE THREAD

**Issue by da-kami** [itchysats/10101#278]
* Estimate fee, calculate fee in sats
* Use wallet balance minus fees for the open channel amount

Max channel amount (sats): 2 ^ 24 -1
We can default to that if our amount is higher

**Comment by bonomat** [comment]
> Max channel amount: 2 ^ 24 -1

https://github.com/itchysats/rust-lightning/blob/2a0edd5c4b012ab6b166ee1c5a68e6974b93dcb2/lightning/src/ln/channel.rs#L865

**Comment by bonomat** [comment]
in sats it is : `16777216`
