### ISSUE TITLE
Improve Receive Bitcoin

### ISSUE THREAD

**Issue by da-kami** [itchysats/10101#285]
# Receive Bitcoin

![simulator_screenshot_BF00C236-64C5-4B99-8B58-5A2A7680287C](https://user-images.githubusercontent.com/224613/203012342-29159d18-bd0d-4447-969a-8e15ea05274b.png)

- Make it possible to see the whole address
- `Copy Address` should close the `Receive Bitcoin` screen. Maybe rename it to close?
- Add a 10101 logo into the QR code

_Originally posted by @bonomat in https://github.com/itchysats/10101/discussions/273#discussioncomment-4193813_

note: We have ot check if the library allows us to add a logo to the QR, if not this can hardly be achieved.

**Comment by bonomat** [comment]
> Add a 10101 logo into the QR code

Looks like the library supports embedding images: https://pub.dev/packages/qr_flutter
