### ISSUE TITLE
Pending after receiving over lightning does not go away

### ISSUE THREAD

**Issue by da-kami** [itchysats/10101#313]

**Comment by bonomat** [comment]
Taking over @klochowicz

**Comment by bonomat** [comment]
Unasigning myself if someone else wants to have a look.

**Comment by bonomat** [comment]
Additional info: 

- payment from `ldk-sample` to `maker` works
- payment from `maker` to `ldk-sample` works
- keysend from `ldk-sample` to `maker` work

- payment from `taker` to `maker` works
- payment from `maker` to `taker` works.

This makes me think that our code is correct but it has something todo with how we store state.
It could be that the `channel_manager` or `key_store` does not know about the hash/secret when receiving the payment and hence does not accept the payment.

**Comment by klochowicz** [comment]
@bonomat did you try `ldk-sample` or `ldk-bdk-sample`? 
was this an outgoing channel from the sample to the maker?

**Comment by bonomat** [comment]
> @bonomat did you try `ldk-sample` or `ldk-bdk-sample`? was this an outgoing channel from the sample to the maker?

I used our `ldk-sample` fork: https://github.com/itchysats/ldk-sample/

I've always opened a channel to the maker from either `taker` or `ldk-sample`

**Comment by klochowicz** [comment]
> 

can you check whether it works for you with `ldk-bdk-sample`? https://github.com/klochowicz/ldk-bdk-sample

I can't get the payment to work this way now:
`{"status":500,"title":"Failed to pay lightning invoice","detail":"LightningError { err: \"Failed to find a path to the given destination\", action: IgnoreError }"}%`

which is weird, I have an open and usable channel  direct channel with the other party, and the destination is correct.

**Comment by klochowicz** [comment]
I think I found something, I managed to successfully pay the taker.

**Comment by bonomat** [comment]
> I think I found something, I managed to successfully pay the taker.

woop woop... i'm curious :)

**Comment by klochowicz** [comment]
> > I think I found something, I managed to successfully pay the taker.
> 
> woop woop... i'm curious :)

was too excited I think! I got around some of the errors, but I still get the one you mentioned. 
Added some in-between PR, and continuing the work:
https://github.com/itchysats/10101/pull/349
