### ISSUE TITLE
Add testnet configuration for released app

### ISSUE THREAD

**Issue by holzeis** [itchysats/10101#336]
In case the app is released it should point to the testnet maker, etc. instead of regtest.

**Comment by klochowicz** [comment]
it seems it should be enough to swap the `maker_pk()` to hard-coded testnet key in the release mode?

**Comment by holzeis** [comment]
> it might be enough to swap the `maker_pk()` to hard-coded testnet key in the release mode?

Not just the public key, but also the endpoint and the network. - network is currently provided through flutter though. For consistency this should probably also be configured in `wallet.rs` (still not a fan of managing configuration in code 🙈 )
