### ISSUE TITLE
Hide open channel card if channel is in creation

### ISSUE THREAD

**Issue by holzeis** [itchysats/10101#337]
The open channel card should be gone after successfully initiating a channel. It might reappear if eventually the channel creation failed, but keeping it in the meantime will confuse the user and may break things if the user retries to open the channel.

An easy quick fix could be a simple timeout, which waits for a lightning balance. If within the timeout nothing changed the card could reappear again.

**Comment by da-kami** [comment]
At the moment `OpenChannel` allows to press the button multiple times which should be prevented somehow.
Disable the button upon click and add a spinner.
