### ISSUE TITLE
Wallet dashboard icons should be centered

### ISSUE THREAD

**Issue by klochowicz** [itchysats/10101#353]
![image](https://user-images.githubusercontent.com/8319440/203699583-453bcc02-910b-4bf1-9846-d7b4776da45a.png)

**Comment by holzeis** [comment]
wasn't that originally to scroll horizontally?

**Comment by klochowicz** [comment]
added this minor UI improvement to the scope, as with 3 icons it's really weird to not have them centered.

**Comment by holzeis** [comment]
wild thought, but I would even remove these icons from the dashboard. 🙈

**Comment by klochowicz** [comment]
> wild thought, but I would even remove these icons from the dashboard. 🙈

I would re-open that thought after the tournament (@da-kami had pretty strong feelings about them before) . I'll try to center them for now.
