### ISSUE TITLE
Payment detail page

### ISSUE THREAD

**Issue by da-kami** [itchysats/10101#354]
When clicking on a payment in the list we should get a payment detail page that shows the information from the list tile *plus* some additional info as listed below:

- on-chain
    - link to mempool.space link for the transaction (depending on the network)

Not sure we have to add additional info for off-chain payments yet, one thing I could imagine is:

- off-chain
    - information concerning the counterparty / channel

**Comment by klochowicz** [comment]
for off-chain, it can show you the description at least - maybe the channel status too?
