### ISSUE TITLE
Could not retrieve short channel id

### ISSUE THREAD

**Issue by holzeis** [itchysats/10101#369]
The error is reproducible by the following steps

1. Fund on-chain wallet
2. Open channel
3. faucet
4. Open cfd

```
{Failed to open CFD: Could not retrieve short channel id} {FfiException(RESULT_ERROR, Could not retrieve short channel id, null)}
```

**Comment by holzeis** [comment]
I think this is the same bug we get on testnet. Can't verfiy without logs though.

**Comment by klochowicz** [comment]
did you have more than one channel open with the maker? I will try to reproduce it now.

**Comment by klochowicz** [comment]
hm, according to the docs for `short_channel_id` 

> 	/// This will be `None` as long as the channel is not available for routing outbound payments.

**Comment by da-kami** [comment]
> The error is reproducible by the following steps
> 
>     1. Fund on-chain wallet
> 
>     2. Open channel
> 
>     3. faucet
> 

You mean you fund the on-chain wallet again?

>     4. Open cfd
> 
> 
> ```
> {Failed to open CFD: Could not retrieve short channel id} {FfiException(RESULT_ERROR, Could not retrieve short channel id, null)}
> ```

Was the transaction that opened the channel already confirmed? If not the channel will not be usable I think.

**Comment by bonomat** [comment]
> You mean you fund the on-chain wallet again?

I think he means he mined a block.

**Comment by da-kami** [comment]
> > You mean you fund the on-chain wallet again?
> 
> I think he means he mined a block.

Ah, right, because it was the local setup - then what I said is irrelevant!

**Comment by klochowicz** [comment]
@holzeis has this repeated itself since then? have you tried to clean your data dirs or both side? I believe I have run into it in the past
