### ISSUE TITLE
Opened a channel with the maker that's insufficient for opening any CFD

### ISSUE THREAD

**Issue by klochowicz** [itchysats/10101#372]
I've opened a channel that's not big enough to open a CFD due to the arbitrary constraint of our 100 USD (which is super confusing for the user, as there's no label about it whatsoever). 

IMHO we should either:
- prevent opening the channel if it doesn't make sense 
- relax the arbitrary constraint. Ideally, I would like to play $5 dollar with a leverage x50. 🤪

it is even more troubling that the user has no control of closing that channel to fix this error - there's no way of recovering from it.

**Comment by da-kami** [comment]
> prevent opening the channel if it doesn't make sense

I would do that, we could just set a minimum amount.
Additionally we should add more validation to the CFD offer screen because I don't think we can use the complete balance but have to keep some sats in the Lightning wallet. @luckysori would you know the minimum sats that have to be in the wallet from the top of your head?

**Comment by da-kami** [comment]
> it is even more troubling that the user has no control of closing that channel to fix this error - there's no way of recovering from it.

This is a feature we just left for "after the tournament" - I think we can write a ticket and add it. The biggest question around it is how to generally introduce "channel management" in the design. Initially we thought about putting it in the settings, but maybe it needs to be more present. We could just add it to the Lightning wallet as additional action + child-screen for explanation and confirmation. 
I captured https://github.com/itchysats/10101/issues/373 for this.

**Comment by bonomat** [comment]
> relax the arbitrary constraint. Ideally, I would like to play $5 dollar with a leverage x50. 🤪

I'm in favor of this. Let's remove this requirement and make the quantity an input field with arbitrary amounts. we can still limit it to 1k though.

**Comment by holzeis** [comment]
It has been decided in the objective alignment to follow the suggestions of the ticket, relaxing the constraints on opening a cfd. Captured here https://github.com/itchysats/10101/issues/405.

@klochowicz I noticed that ticket, after creating https://github.com/itchysats/10101/issues/405 - we can also close the other one, if we want to stick with that ticket.

**Comment by klochowicz** [comment]
> It has been decided in the objective alignment to follow the suggestions of the ticket, relaxing the constraints on opening a cfd. Captured here #405.
> 
> @klochowicz I noticed that ticket, after creating #405 - we can also close the other one, if we want to stick with that ticket.

does your ticket solve the bug? ie. prevents being able to open a channel with less amount than minimum quantity? if yes, this ticket can be closed :-)

**Comment by holzeis** [comment]
> does your ticket solve the bug? ie. prevents being able to open a channel with less amount than minimum quantity? if yes, this ticket can be closed :-)

It only addresses 
> relax the arbitrary constraint. Ideally, I would like to play $5 dollar with a leverage x50.

so I guess for the other part we can keep that ticket.

**Comment by bonomat** [comment]
I think this was solved with @da-kami PR https://github.com/itchysats/10101/pull/454 which allows quantities of [1,1000]
