### ISSUE TITLE
Add `close channel ` action to the Lightning wallet actions in the UI

### ISSUE THREAD

**Issue by da-kami** [itchysats/10101#373]
As mentioned in https://github.com/itchysats/10101/issues/372 the user should have the means to back out of the channel if something goes wrong. 

The easiest way to achieve this is adding another action to the FAB in the Lightning wallet that allows the user to close the channel. 
We *could* restrict this to only allow it if there is no CFD currently open, to keep the scope smaller.

**Comment by klochowicz** [comment]
perhaps `Settings` in actually the best way. FAB could trigger a close far too easily.

**Comment by da-kami** [comment]
The FAB does only trigger going to a child screen (as for Send/Receive) and then the user has to confirm the action. I think this is safe enough and more intuitive than hiding this in the settings.
