### ISSUE TITLE
Insufficient funds errors when opening a channel are confusing

### ISSUE THREAD

**Issue by klochowicz** [itchysats/10101#374]
env: testnet

I have tried to open a channel, and I repeatedly was unable to do so, even when I changed the amount to be well within range (like 20% of my confirmed balance). I suspect that the maker did not have balance, and it was reporting insufficient funds the same way as the taker.

Eventually I opened a crazy low channel and ended up with #372 

This is quite a blocker, as this point of friction can discourage people from actually testing our app.

**Comment by luckysori** [comment]
Was this fixed with https://github.com/itchysats/10101/pull/370/commits/51d491c5d2691eca2a58d71bb6e9b5773db89705?

**Comment by klochowicz** [comment]
> Was this fixed with [51d491c](https://github.com/itchysats/10101/commit/51d491c5d2691eca2a58d71bb6e9b5773db89705)?

It hasn't - it still says it happened due to insufficient funds (error is from the other party). I'll see to add more context.
