### ISSUE TITLE
Release 10101 to testflight

### ISSUE THREAD

**Issue by holzeis** [itchysats/10101#409]
- Build and release an iOS app: https://docs.flutter.dev/deployment/ios#release-your-app-on-testflight
- Distribute an app using TestFlight: https://help.apple.com/xcode/mac/current/#/dev2539d985f

**Comment by bonomat** [comment]
Solved, follow this steps

1. ping @bonomat: he is the only one who can publish it at the moment 😅
2. run `make deps && make gen && make native && make ios && NETWORK=regtest flutter run`
3. run `flutter build ios`
4. run `flutter build ipa`
5. `xcrun altool --upload-app --type ios --file ./build/ios/ipa/10101.ipa --apiKey $API_KEY --apiIssuer $APP_ISSUER_ID`

https://appstoreconnect.apple.com/apps/6444779334
