### ISSUE TITLE
Add on-boarding tour

### ISSUE THREAD

**Issue by holzeis** [itchysats/10101#411]
Upon the first start of the app the use should get a tour through the app explaining whats what and how to CFD!

**Comment by bonomat** [comment]
We should have a look into https://bitcoin.design/guide/designing-products/common-user-flows/#software-onboarding
They have some nice on-boarding flows we could copy.

**Comment by da-kami** [comment]
Would an additional onboarding tour on first start be enough (e.g. using https://pub.dev/packages/onboarding) or wold you add onboarding to different parts of the application?

I think in the long run we need *some* onboarding for different parts, i.e. explain what the wallet backup means, have simple onboarding into the flow of fund on-chain -> open channel -> trade, some onboarding into CFD trading.

For now I propose to just add some initial onboarding using a package like https://pub.dev/packages/onboarding where we explain that:

1. There is an on-chain and a lightning wallet
2. The user has to fund the on-chain wallet to open a channel
3. Once the channel was opened the user can trade.

**Comment by bonomat** [comment]
I would just go for a single on-boarding screen for the whole app, welcome the user and explain what this app is about. 

The plugin you propose seems reasonable to me :)

**Comment by da-kami** [comment]
OK! I can give that a go. I'll assign myself.
