### ISSUE TITLE
Add send feedback button from within the app

### ISSUE THREAD

**Issue by holzeis** [itchysats/10101#414]
The user should be able to send feedback to the app.

**Acceptance Criterias**

- [x] The button click should open an email template on the users phone
- [x] The logs should be automatically exported to file (zipped?) and attached to the email

**Comment by holzeis** [comment]
related to https://github.com/itchysats/10101/issues/105

**Comment by klochowicz** [comment]
I don't see attaching logs as mandatory part of user's feedback - as such, it's a separate feature (probably not in scope for 0.3.0?)
note that the logs will be attached to crash reports in TestFlight anyway.

**Comment by holzeis** [comment]
well not mandatory, but definitely helpful. Imagine the user fails to do something, without the app crashing. It would be nice to have access to the taker logs to see what has happened.

we can put it to the very bottom of the backlog though.
