### ISSUE TITLE
Handle channel events properly

### ISSUE THREAD

**Issue by holzeis** [itchysats/10101#420]
Currently we do not act on the channel events, e.g. `ChannelReady`, `ChannelClosed` etc. We should update our channel state in regards to the events and update the user correspondingly.

e.g. only show that the channel is ready if we have received the `ChannelReady` event.

**Comment by holzeis** [comment]
A dedicated channel view might be helpful to depict the individual channel state to the user - #338

**Comment by klochowicz** [comment]
where did you see `ChannelReady` event? I see only `ChannelClosed`, which is for "channels that are in the process of closure", so we can't really tell whether this got closed.
The way to ensure that a channel has been properly closed would be monitoring on-chain for the transactions resolving the channel.... - similar for opening a channel.

**Comment by holzeis** [comment]
> where did you see `ChannelReady` event? I see only `ChannelClosed`, which is for "channels that are in the process of closure", so we can't really tell whether this got closed. The way to ensure that a channel has been properly closed would be monitoring on-chain for the transactions resolving the channel.... - similar for opening a channel.

You can find the channel ready event on the maker side. We don't have to handle the channel events though, we could as well use the `ChannelDetails` `is_channel_ready` and `is_usable`. @bonomat was looking into that.

**Comment by bonomat** [comment]
related to #485
