### ISSUE TITLE
Only show app ready, once the balance has been synchronised

### ISSUE THREAD

**Issue by holzeis** [itchysats/10101#421]
It could get very frightening if the app loads completely blank 😅 So in order to safe some unnecessary sweat I suggest we only show the app ready once at least the balance has been synchronised. I guess having the history would also be nice before showing the app ready.

**Comment by bonomat** [comment]
An alternative would to show that the wallet is syncing

**Comment by luckysori** [comment]
I think it would be preferable to show the balance as "syncing", like Philipp suggests. 

I think it's preferable to let the user access the app ASAP. I know if I'm stuck on a splash screen for too long I ask myself two questions:

- Is the app broken?
- Is there something else I'd rather do? 😛

**Comment by holzeis** [comment]
I agree, the only downside of the alternative is that it takes more design and implementation effort.

**Comment by bonomat** [comment]
Note, that you should always see something once we have https://github.com/itchysats/10101/issues/396 implented.

**Comment by luckysori** [comment]
> Note, that you should always see something once we have #396 implented.

Maybe it's enough to do #396 then?

**Comment by holzeis** [comment]
tested on latest main - it seems with #396 the balance and history is loaded fast enough to get ready before the splash screen disappears.
