### ISSUE TITLE
Bitcoin balance and transactions are not synchronised

### ISSUE THREAD

**Issue by luckysori** [itchysats/10101#427]
A small UI inconsistency:

https://user-images.githubusercontent.com/9418575/204429513-af9ed3c6-470c-4c0b-af96-d2048baf5888.mp4

The transaction appears before the balance is updated.

**Comment by bonomat** [comment]
The issue might come from us syncing the frontend in two steps: 
https://github.com/itchysats/10101/blob/a7c7e8bc1e2ab2a55cf4295630d8f80a79807bd2/lib/main.dart#L228-L231

**Comment by bonomat** [comment]
Ok, it's not that :) We might need to use a single `ChangeNotifier` for balances and payment history to synchronize the update.

I'll unasign myself as it doesn't look like a quick fix.

**Comment by holzeis** [comment]
fixed with #566
