### ISSUE TITLE
`Channel not available` error when trying to settle a CFD

### ISSUE THREAD

**Issue by da-kami** [itchysats/10101#428]
happened on local regtest setup.

<img width="543" alt="image" src="https://user-images.githubusercontent.com/5557790/204437360-d87cb880-5df2-4236-9773-d9814518c9fc.png">

**Comment by da-kami** [comment]
Note: Restart of the maker fixed it (without restarting the taker), so I think this is related to the connection management as well!

**Comment by holzeis** [comment]
@da-kami Are you sure the channel got created successfully? Including a grace period to verify it hasn't been closed shortly afterwards?

**Comment by da-kami** [comment]
> 

I had a CFD open, so I assume yes 😅

**Comment by holzeis** [comment]
That's true, opening shouldn't have worked if the channel wasn't ready in the first place.

**Comment by bonomat** [comment]
can be solved together with https://github.com/itchysats/10101/issues/485 on top of https://github.com/itchysats/10101/pull/496
