### ISSUE TITLE
android: Failed to load dynamic library 'libten_ten_one.so'

### ISSUE THREAD

**Issue by holzeis** [itchysats/10101#44]
Regardless if on the emulated android device or through wireless debugging on the physical android device. The following error gets printed repeatedly in the logs. The app gets started though.

```
E/flutter (29452): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Invalid argument(s): Failed to load dynamic library 'libten_ten_one.so': dlopen failed: library "libten_ten_one.so" not found
E/flutter (29452): #0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:12:43)
E/flutter (29452): #1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:23:12)
E/flutter (29452): #2      dylib (package:ten_ten_one/ffi.io.dart:12:26)
E/flutter (29452): #3      dylib (package:ten_ten_one/ffi.io.dart)
E/flutter (29452): #4      api (package:ten_ten_one/ffi.io.dart:13:32)
E/flutter (29452): #5      api (package:ten_ten_one/ffi.io.dart)
E/flutter (29452): #6      _MyAppState._callExampleFfiOne (package:ten_ten_one/main.dart:41:33)
E/flutter (29452): #7      runPeriodically.<anonymous closure> (package:ten_ten_one/off_topic_code.dart:137:74)
E/flutter (29452): #8      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
E/flutter (29452): #9      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
E/flutter (29452): #10     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
E/flutter (29452): 
```

**Comment by klochowicz** [comment]
did you try running `make deps` first?

**Comment by holzeis** [comment]
yes

**Comment by holzeis** [comment]
> did you try running `make deps` first?

yes

**Comment by klochowicz** [comment]
what steps did you do? did `make android` work? 

I suspect that this would solve your issue (android sim needs different build target): https://github.com/itchysats/10101/pull/53

**Comment by klochowicz** [comment]
did you follow the step suggested in the error message you pasted above? *rustup target install x86_64-linux-android* 

could you please also give more details as previously asked for? ie. which steps have you done? does the problem include both running in simulator or also on the Android mobile? does it work if you run `build native` and just flutter run for macOS target?

Regrettably, I don't have a M1 mac, so I can't reproduce this problem on my box.

**Comment by holzeis** [comment]
Turns out the issue was installing rust through homebrew - which mixed things up. uninstalled rust through brew and followed the recommended installation from https://www.rust-lang.org/tools/install.

**Comment by klochowicz** [comment]
> Turns out the issue was installing rust through homebrew - which mixed things up. uninstalled rust through brew and followed the recommended installation from https://www.rust-lang.org/tools/install.

glad I could help 🙂 I have recommended not using homebrew for Rust previously after I ended up having massive problems with clippy :/

**Comment by holzeis** [comment]
> > Turns out the issue was installing rust through homebrew - which mixed things up. uninstalled rust through brew and followed the recommended installation from https://www.rust-lang.org/tools/install.
> 
> glad I could help 🙂
> 
> I have recommended not using homebrew for Rust previously after I ended up having massive problems with clippy :/

Thanks @klochowicz for the support 🙂 💪
