### ISSUE TITLE
Can't navigate twice to the same action

### ISSUE THREAD

**Issue by holzeis** [itchysats/10101#441]
Very odd, but it appears that when using the back navigation you can't get back to the same page you've just left. You have to firstly move to another page, before the other one can be navigated to again.

![Image](https://user-images.githubusercontent.com/382048/204504508-83e49949-46b1-49eb-b646-79c0481ab64a.gif)

**Comment by bonomat** [comment]
Same goes for other actions as well such as clicking on the fobs in the wallet screen. 
@da-kami : any idea?

**Comment by da-kami** [comment]
Wow, I never noticed that! I am having a look. 

One thing I noticed: This only happens on the `wallet` route, might be related to using `/` as an identifier there. I'll see if I can come up with a quick fix.

**Comment by bonomat** [comment]
thanks for looking into this.
