### ISSUE TITLE
Closing channel requires 1 confirmation before funds are returned

### ISSUE THREAD

**Issue by holzeis** [itchysats/10101#461]
Observed while debugging #440.

Is this delay intended?

---

EDIT: Used to be 6 confirmations, now it's 1 (maybe even 0 and I'm just impatient, but it's definitely not instant as the 2 transactions must be published and found in the mempool or on-chain) thanks to https://github.com/lightningdevkit/rust-lightning/commit/86531aa2ecdc228ae3788fda7332511c08870a69.

As @da-kami pointed out, a reasonable UX must be ensured regardless. The user needs to know that we are waiting for something to happen before the Lightning and Bitcoin balances are updated.

**Comment by bonomat** [comment]
It looks like this is a hard requirement in the ldk: 
https://github.com/itchysats/rust-lightning/blob/f4f1093edc506314484c8d52a40dd155e692394b/lightning/src/chain/channelmonitor.rs#L397-L401

The field `ANTI_REORG_DELAY` is hardcoded to 6, letting us spend this output only after 6 confirmation

**Comment by da-kami** [comment]
Interesting - do we see it as `pending` balance or not at all?

**Comment by bonomat** [comment]
> Interesting - do we see it as `pending` balance or not at all?

not at all until after the 6 blocks

**Comment by da-kami** [comment]
> > Interesting - do we see it as `pending` balance or not at all?
> 
> not at all until after the 6 blocks

That sucks, that's definitely not a nice UX :/

**Comment by luckysori** [comment]
I've updated LDK to deal with this: https://github.com/lightningdevkit/rust-lightning/commit/86531aa2ecdc228ae3788fda7332511c08870a69. 10101 PR incoming.
