### ISSUE TITLE
Collab close transaction uses wrong amounts

### ISSUE THREAD

**Issue by bonomat** [itchysats/10101#475]
it looks like that we use the wrong amounts when collaboratively closing: 

how to reproduce

1. open channel
2. open position
3. close position (and make a loss or profit)
4. close channel
5. get initial funding and win!

Step 5 is wrong obviously :)

**Comment by luckysori** [comment]
Fixed with https://github.com/lightningdevkit/rust-lightning/commit/10b69c99ea13c6c2c55c74a7497764a6303b9d34, I'll create a PR shortly.
