### ISSUE TITLE
Can't see navigation menu

### ISSUE THREAD

**Issue by bonomat** [itchysats/10101#514]
When coming onto this screen, the keyboard pops up by default and it is not possible to navigate to open positions . 

![image](https://user-images.githubusercontent.com/224613/205406121-cb3f8d2d-975c-498c-a377-714b1a20e0f7.png)

**Comment by da-kami** [comment]
This might be a regression bug, on android I don't have a FAB at all if there is no channel. (I closed the keyboard and there is no FAB.) I don't think this screen should behave like this.

![image](https://user-images.githubusercontent.com/5557790/205520326-3f7ed30e-64f7-471f-9386-ea97b2e8c554.png)

**Comment by bonomat** [comment]
> This might be a regression bug, on android I don't have a FAB at all if there is no channel. (I closed the keyboard and there is no FAB.) I don't think this screen should behave like this.

That's by design: if there is no action, there is no FAB

**Comment by da-kami** [comment]
> That's by design: if there is no action, there is no FAB

OK, I was not aware that this was changed. Previously we kept the navigation to the subscreen (where `Confirm` was disabled) so the user can get a better feeling of the app even if the channel is not open yet.

**Comment by da-kami** [comment]
> When coming onto this screen, the keyboard pops up by default and it is not possible to navigate to open positions .

One way to fix this is to turn the auto-open of the keyboard off. I;ll create a PR :)
