### ISSUE TITLE
Display the version the user is running in the app, and add it to metadata when sending feedback

### ISSUE THREAD

**Issue by da-kami** [itchysats/10101#521]
Without the version the user is running it can be very hard to trace problems.
Given that we are not sure which version exactly will make it on the user's phone we should send the version and also tell it to the user.

**Comment by klochowicz** [comment]
it might be good to display the bitcoin network somewhere too, it's reassuring for people to know they're playing on testnet or regtest. :-)

**Comment by da-kami** [comment]
> it might be good to display the bitcoin network somewhere too, it's reassuring for people to know they're playing on testnet or regtest. :-)

Agreed! I will see to include that in the PR
