### ISSUE TITLE
Keyboard blocks view of open-CFD screen

### ISSUE THREAD

**Issue by luckysori** [itchysats/10101#527]
When navigating to the open-CFD screen, the quantity text field is pre-selected. This automatically opens the keyboard, blocking the view of relevant information for the user.

Tested on iPhone SE.

**Comment by luckysori** [comment]
So is this one actually fixed, @da-kami?

**Comment by da-kami** [comment]
The pre-selection was removed in #515 - if that solves this issue it should be fixed.
