### ISSUE TITLE
Create BIP-39 compatible BDK wallet

### ISSUE THREAD

**Issue by klochowicz** [itchysats/10101#68]
Upon the first start of the application, a new bitcoin wallet should be created from with a seed compatible with BIP39.
This should allow us to export the seed words.

**Comment by bonomat** [comment]
Additional [Bip84](https://github.com/bitcoin/bips/blob/master/bip-0084.mediawiki) please. BDK has some [convenience methods](https://bitcoindevkit.org/docs-rs/bdk/nightly/latest/bdk/descriptor/template/struct.Bip84.html) for this.
