### ISSUE TITLE
Create dashboard widget

### ISSUE THREAD

**Issue by holzeis** [itchysats/10101#85]
![Image](https://user-images.githubusercontent.com/382048/198895742-f1960bfa-85ca-449e-8f2c-3d52b0e29a72.png)

Acceptance Criterias

- Build dedicated widget for the balance.
- Create card for cfd trading navigate to another route. (empty screen)
- Create card for sports betting (disabled)
- Add fund wallet with bitcoin card - navigate to another route. (empty screen)

**Comment by holzeis** [comment]
I don't know if we want to stick with the bottom bar.

**Comment by holzeis** [comment]
I created a sub ticket for the balance widget. https://github.com/itchysats/10101/issues/90

**Comment by holzeis** [comment]
@da-kami Can we close that ticket?

**Comment by da-kami** [comment]
Sorry, missed that message, yes, I think this can be closed. Any improvements / changes should be captured in specific follow-up tickets!
