### ISSUE TITLE
Build ldk node (maker)

### ISSUE THREAD

**Issue by holzeis** [itchysats/10101#89]
This is the maker part of the cfd trading. see also #82 for the taker part.

https://lightningdevkit.org/tutorials/build_a_node_in_rust/

This should be implemented as a server.

**Comment by bonomat** [comment]
Here is a sample application which we should be able to use: https://github.com/lightningdevkit/ldk-sample/

**Comment by holzeis** [comment]
This ticket is dependent on the bdk ldk integration done in #82

**Comment by klochowicz** [comment]
Initial maker node got added in: #177
